APPLICATION_PROFILE=complete-desktop
DEVOPS_TOOLS_ON_HOST=false
MARKDOWN_EDITOR=ghostwriter
MARKTEXT_AUTO_INSTALL=false
VSCODE_REMOTE_SSH_REQUIRED=true
BRAVE_REQUIRED=true
BITWARDEN_REQUIRED=true
ONLYOFFICE_REQUIRED=true
DRAWIO_REQUIRED=true
FLATPAK_SYSTEM_APPS=true
